### ISSUE TITLE
false Positive from manifest_whitespace_opening_bracket_before with structured facts

### ISSUE THREAD

**Issue by Dan33l** [kuleuven/puppet-lint-manifest_whitespace-check#21] opened 2022-12-19 16:35 UTC
I am using a custom fact like this : `$facts['customfact_name'][$variable]`

I am getting message : `ERROR: there should be a single space before an opening bracket`.

The bracket is used with `facts` and must be without space.

**Comment by jovandeginste** [comment] 2022-12-19 18:47
Sounds like duplicate of #17; can you confirm you are running the latest version?

**Comment by Dan33l** [comment] 2022-12-20 12:48
In `Gemfile.lock`, i get `puppet-lint-manifest_whitespace-check (0.2.7)`.

**Comment by jovandeginste** [comment] 2022-12-21 09:29
I added some tests and pushed v0.2.8 - maybe something went wrong when building v0.2.7, but I'm not sure.
Can you try and update to that version?

**Comment by Dan33l** [comment] 2022-12-21 10:03
I am getting same error message with `0.2.8`.

**Comment by Dan33l** [comment] 2022-12-21 13:21
I meet this error message on a public code. Perhaps it can help to debug :
* the code: https://gitlab.adullact.net/fcombernous/restic/-/tree/102-use-pdk-2-5-0-and-ruby-2-7-5
* the corresponding CI job:  https://gitlab.adullact.net/fcombernous/restic/-/jobs/118017

**Comment by jovandeginste** [comment] 2023-01-05 08:14
The error is because of the `{ [] }` at the [end of the line](https://gitlab.adullact.net/fcombernous/restic/-/blob/102-use-pdk-2-5-0-and-ruby-2-7-5/manifests/backups.pp#L21)

**Comment by jovandeginste** [comment] 2023-01-05 08:22
I added it as a test case and fixed it in master

**Closed as completed** 2023-01-05 08:22 UTC

**Comment by jovandeginste** [comment] 2023-01-05 08:30
It is now released as 0.2.9 - can you confirm?

**Comment by Dan33l** [comment] 2023-01-09 15:31
With puppet-lint-manifest_whitespace-check (0.2.9), i can confirm that linter is passing without error message.

Thank you.
